<div class="wrapper d-flex align-items-stretch">
    <x-header />
    <div id="content" class="p-4 p-md-5 pt-5">
        <div id="block">
            <h1>Laravel Request Lifecycle</h1>
            <p>The lifecycle of a request in Laravel involves several stages from the moment a request is received to when a response is sent back to the client. Here's a brief overview of the Laravel request lifecycle:</p>
            <img src="{{asset('images/flow.webp')}}">
        </div>
        <div id="block">
            <h3>Auto Loader:</h3>
            <p>The entry point for all requests to a Laravel application is the <code>public/index.php file</code>. All requests are directed to this file by your web server configuration. The <code>index.php</code> file doesn't contain much code. Rather, it is a starting point for loading the rest of the framework.<br><br>It loads the auto loader files which is generated by composer.<br><br>Then it retrieves an instance of the Laravel application from <code>bootstrap/app.php</code> script. Laravel itself creates an instance of the application, is the initial/first step.</p>
        </div>
        <div id="block">
            <h3>Kernel:</h3>
            <p>Next step will occur on the Kernel part of the application.<br><br>The incoming request is sent to either the HTTP kernel or the console kernel, depending on the type of request that is entering the application .These two kernels serve as the central location that all requests flow through.<br><br>HTTP kernel, which is placed in <code>app/Http/Kernel.php</code>. It just receive a Request and return a Response. Bootstrappers that are defined by the Kernel class, which configures error handling, configure logging, detect environments and other tasks to be done before the request handled.<br><br>HTTP Kernel will define the list of middleware that are passed through before handled by application.</p>
        </div>
        <div id="block">
            <h3>Service Providers:</h3>
            <p>Next step of the kernel is to load service providers as part of the bootstrapping action. Providers that are needed for the application are placed in config/app.php configuration file.<br><br>While the register method calls, all the providers will be registered. Once all providers are registered, then boot method will be called.</p>
        </div>
        <div id="block">
            <h3>Dispatch Request:</h3>
            <p>Once the application have been bootstrapped and all service providers are registered and booted, the request will be handed over to the router for dispatching. The router will dispatch the request to a route or controller, as well as run any route specific middleware.</p>
        </div>
        <div id="block">
            <h3>Router:</h3>
            <p>Now request will be dispatched by the Router and it will end up with the views as shown below:<br><br>Router will direct the HTTP Request to a Controller or return a view or responses directly by omitting the controller. These routes will be placed in <code>app/routes.php</code>.<br><br>Controller <code>app/controllers/</code> performs specific actions and sends data to a View.<br><br>View app/views/ formats the data appropriately, providing the HTTP Response.</p>
        </div>

    </div>
</div>
<x-footer_files />
</body>

</html>